# Generated by Django 2.1.7 on 2019-03-20 13:19

from django.db import migrations
import enumchoicefield.fields
import wagtailvideos.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0010_video_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscode',
            name='media_format',
            field=enumchoicefield.fields.EnumChoiceField(default=wagtailvideos.models.MediaFormats(4), enum_class=wagtailvideos.models.MediaFormats, max_length=7),
        ),
    ]
