# Generated by Django 2.1.7 on 2019-03-20 16:02

from django.db import migrations, models
import wagtailvideos.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0011_auto_20190320_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='looped',
            field=models.BooleanField(default=False, verbose_name='looped'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=wagtailvideos.models.get_upload_to, verbose_name='thumbnail'),
        ),
    ]
